### ISSUE TITLE
getting unhandled exception when trying to register new job

### ISSUE THREAD

**Issue by klrmn** [FiloSottile/travis-cron#1]
i tried to register my job (klrmn/pytest-rerunfailures)...the first time it sent me thru asking for github credentials, which i okayed. and then got an 'unhandled exception' page. i waited a week to see if it had crashed after the important parts, but there was no sign of a run triggered by the service.

so i tried registering it again. i got 'unhandled exception' immediately, with the url http://traviscron.pythonanywhere.com/callback?code=8c9eae2ce5a242c2d145&state=67990841a07b23ea414db0b3a39282

chrome on OSX.
let me know if you need more info.

**Comment by FiloSottile** [comment]
It seems like Django can't get info from your `request.session`. Are you blocking cookies?

**Comment by klrmn** [comment]
that's rather strange. i just tried it again using FF17 on OSX and got the same error (didn't ask me for github creds). i've got cookies turned on in both chrome and FF (i imagine my browsing and django development experience would be horrendous if i didn't, but i double-checked).

**Comment by FiloSottile** [comment]
Ok, I was staring at the error that is raised by reloading the `/callback` page, thing that rightfully (well, badly handled, but rightfully) fail. The real error is that I get a 403 HTTP error when I hit Travis to trade the GH token for a Travis one.

Since I am not supposed to access user's GH, I don't store the GH access_token, so I can't add your entry manually.

Trying to reproduce it.

**Comment by FiloSottile** [comment]
Could you check that `Travis Cron Trigger` is listed as `access public repositories` in https://github.com/settings/applications?

**Comment by FiloSottile** [comment]
Acc, just reproduced on my account. I hope it's not Travis side.

**Comment by FiloSottile** [comment]
Ok, fixed thanks to the Travis guys.
We're back on track, please register one last time ;)

**Comment by klrmn** [comment]
looks like it worked this time, thanks!

**Comment by FiloSottile** [comment]
And accepted!

You're welcome, let me know any feedback you might have.
