### ISSUE TITLE
▶ oiim/scraper

### ISSUE THREAD

**Issue by abernier** [FiloSottile/travis-cron#2]
Hi,

Recently, I've registered a project on http://traviscron.pythonanywhere.com/ which is oiim/scraper

Actually it is ◼ disabled. Is it possible ▶ it ?

Thank you

**Comment by FiloSottile** [comment]
Done! Sorry I was a bit backlogged, and also had to fix the service.

It's running now, I changed it to Bidiem not to hit Travis servers too heavily, if it is important to have it run each 24h, just let me know :)

Happy testing :sparkles:
